In [1]:
# import data
import pandas as pd
import tensorflow as tf

In [2]:
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
# onehotincoding
incode = pd.get_dummies(iris)
incode.head()
print(incode.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [4]:
# divide
alone = incode[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
depand = incode[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(alone.shape, depand.shape)

(150, 4) (150, 3)


In [24]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [25]:
# learn model
model.fit(alone, depand, epochs=1000, verbose=0)
model.fit(alone, depand, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1019 - accuracy: 0.9467
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0856 - accuracy: 0.9533
Epoch 3/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1130 - accuracy: 0.9400
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0690 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0699 - accuracy: 0.9867
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0695 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0790 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0673 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0714 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 5ms/step - loss: 0.0739 - accuracy: 0.9733


In [16]:
model.predict(alone[0:5])

array([[9.9999201e-01, 8.9295057e-08, 7.9158353e-06],
       [9.9999535e-01, 5.1062308e-08, 4.5958163e-06],
       [9.9999523e-01, 5.6449064e-08, 4.7678122e-06],
       [9.9999547e-01, 4.7793353e-08, 4.5461052e-06],
       [9.9999011e-01, 1.0715835e-07, 9.7784632e-06]], dtype=float32)

In [17]:
print(depand[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [18]:
# 
model.get_weights()

[array([[-0.30277982,  0.38231775,  0.34445643,  0.34524176, -0.13765483],
        [-0.07709859,  0.20896997,  0.5410608 ,  0.64214957,  0.45320058],
        [ 0.83643293,  0.40732402, -1.0099665 , -1.027654  , -0.16824262],
        [ 0.6072803 , -0.33364156, -0.9622062 , -1.1695988 , -1.3828335 ]],
       dtype=float32),
 array([-0.54779196,  0.28127712,  0.31277326,  0.46849668,  0.32526955],
       dtype=float32),
 array([[-0.85652053, -0.9743365 , -1.1014377 , -0.68760496, -0.59747654],
        [ 0.3514095 , -0.34302247, -0.2110254 , -0.5337259 , -0.6978659 ],
        [-1.9925256 , -0.7137394 , -0.62934816, -0.7077198 , -0.07301335],
        [-1.6374428 ,  0.21801068, -0.14206322,  0.5701136 ,  0.3540807 ],
        [-1.3769231 , -1.0328423 , -0.1143641 , -1.1186833 , -1.1441773 ]],
       dtype=float32),
 array([0.47253224, 0.7307266 , 0.83594674, 0.6160676 , 0.56841874],
       dtype=float32),
 array([[ 1.7326628 , -1.097973  , -1.7992691 ,  0.13747892, -1.4760573 ],
        [-1.5